# permissions for end users to edit automons.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: automon-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: mytool
    app.kubernetes.io/part-of: mytool
    app.kubernetes.io/managed-by: kustomize
  name: automon-editor-role
rules:
- apiGroups:
  - tool.liuxiangbiao.com
  resources:
  - automons
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tool.liuxiangbiao.com
  resources:
  - automons/status
  verbs:
  - get
